name: lint-test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: '3.11'}
    - run: pip install jax jaxlib
    - run: pip install .[dev,docs]
    - run: ruff check .
    - run: mypy bsde_dsgE
    - run: pytest -q
      env:
        NOTEBOOK_FAST: '1'
    - run: sphinx-build -n -b html docs docs/_build/html
  table1-check:
    if: ${{ env.STRICT_TABLE1 == '1' }}
    runs-on: ubuntu-latest
    env:
      STRICT_TABLE1: ${{ env.STRICT_TABLE1 }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: '3.11'}
    - run: pip install jax jaxlib
    - run: pip install .[dev]
    - name: Strict Table 1 check (moments)
      run: python scripts/check_table1.py --calib data/probab01_table1.json --steps 50 --paths 16
      env:
        STRICT_TABLE1: '1'
